- name: Load system specific variables
  include_vars:
    file: "{{ ansible_facts.os_family }}.yml"
  tags:
    - always

- import_tasks: install.yml
  tags:
    - strongswan
    - strongswan_install

- import_tasks: config.yml
  tags:
    - strongswan
    - strongswan_config

- import_tasks: service.yml
  tags:
    - strongswan
    - strongswan_service
