- name: Reload strongswan
  command: "{{ strongswan_cmd }} reload"
  listen: strongswan:reload
  loop: "{{ strongswan_enabled | ternary(strongswan_services, []) }}"

- name: Restart strongswan
  service:
    name: "{{ item }}"
    state: restarted
  listen: strongswan:restart
  loop: "{{ strongswan_enabled | ternary(strongswan_services, []) }}"
